#!/usr/bin/env bash
#prints at 8th (good luck), at 4th (bad luck) and Best School for the rest

i=0
while [ $i -lt 10 ]
do
if [ $i = 3 ]
then
echo "bad luck"
elif [ $i = 7 ]
then
echo "good luck"
else
echo "Best School"
fi
i=$((i+1))
done
