#!/usr/bin/env bash
#checks the status of the file named school

device="./school"

if [ -a "$device" ]
then
	echo "school file exists"
	if [ -s "$device" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$device" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
