#!/usr/bin/env bash
# changes the ip address of local host and facebook.com

echo "8.8.8.8		facebook.com" >> /etc/hosts
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
cp -f ~/hosts.new /etc/hosts
